version: '3.9'

services:
  db:
    image: postgres:12
    container_name: tgk_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tgk_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: DataBase/Dockerfile.dockerfile
    container_name: tgk_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/tgk_db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dockerfile
    container_name: tgk_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  postgres_data: