export const FIELD_MAPPING = {
  "№ п/п": "id",
  "Ст. сметы": "st_smet",
  "Контрагент": "counterparty",
  "Малый или средний бизнес": "is_mal_or_sred_bis",
  "Конфиденциальная информация": "confidentiality_of_information",
  "ИД случая": "id_case",
  "Дата оплаты по договору": "date_payment_agreement",
  "Планируемая дата оплаты": "planned_payment_date",
  "Просрочка": "is_overdue",
  "Сумма": "summ",
  "№ Акт/ТН/УПД": "str_act",
  "№ и дата сч/ф": "str_scf",
  "№ и дата счета": "str_bill",
  "Прочий документ": "other_documents",
  "Комментарий": "comment",
  "Статус": "id_status",
  "№ ЗНО": "id_zno",
  "Дата оплаты": "payment_date",
  "Номер платежного поручения": "id_payment_order",
  "Пользователь": "id_user",
  "Дата создания": "create_data",
  "ОКО": "id_oko"
};