"""Add is_archived to directories

Revision ID: 7b9d31162e4a
Revises: 906c3699c8f9
Create Date: 2025-04-21 23:42:49.655050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9d31162e4a'
down_revision: Union[str, None] = '906c3699c8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ConfidentialityOfInformation', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('StSmet', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('StSmet', 'is_archived')
    op.drop_column('ConfidentialityOfInformation', 'is_archived')
    # ### end Alembic commands ###
