"""add expiration_date to User

Revision ID: 906c3699c8f9
Revises: c074e9b933b3
Create Date: 2025-04-21 22:55:03.131295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906c3699c8f9'
down_revision: Union[str, None] = 'c074e9b933b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('directories')
    op.add_column('users', sa.Column('expiration_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expiration_date')
    op.create_table('directories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('directory_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('st', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_group', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='directories_pkey')
    )
    # ### end Alembic commands ###
