"""Add expiration_date to directories

Revision ID: c9f098340e11
Revises: 7b9d31162e4a
Create Date: 2025-04-21 23:56:19.652054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f098340e11'
down_revision: Union[str, None] = '7b9d31162e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ConfidentialityOfInformation', sa.Column('expiration_date', sa.Date(), nullable=True))
    op.add_column('StSmet', sa.Column('expiration_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('StSmet', 'expiration_date')
    op.drop_column('ConfidentialityOfInformation', 'expiration_date')
    # ### end Alembic commands ###
